'use client';

import { useState, useRef, useEffect, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import TrialModeBanner from '@/components/TrialModeBanner';
import PreviewModal from './components/PreviewModal';
import AIEditChatModal from './components/AIEditChatModal';
import { supabaseCaseStorage, CaseFrontend, Attorney } from '@/lib/supabase/caseStorage';
import { createClient } from '@/lib/supabase/client';
import { useTrialMode } from '@/lib/contexts/TrialModeContext';
import { userProfileStorage, UserProfile } from '@/lib/supabase/userProfileStorage';
import { RotateCcw } from 'lucide-react';

interface CardSection {
  id: string;
  title: string;
  content: string;
}

interface Recipient {
  id: string;
  name: string;
  firm: string;
  address: string;
  phone: string;
  email: string;
}

type SendViaOption = 'Email' | 'Certified Mail' | 'Regular Mail' | 'Fax' | 'Hand Delivery';

interface REInfo {
  caseName: string;
  dateOfLoss: string;
  caseNumber: string;
}

interface SenderInfo {
  name: string;
  firm: string;
  address: string;
  phone: string;
  email: string;
}

// UUID regex for security validation
const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export default function DemandLetterPage() {
  return (
    <Suspense
      fallback={
        <div className="min-h-screen bg-white">
          <Header />
          <div className="p-6 text-gray-600">Loading demand letter generator...</div>
          <Footer />
        </div>
      }
    >
      <DemandLetterPageContent />
    </Suspense>
  );
}

function DemandLetterPageContent() {
  const searchParams = useSearchParams();
  const { isTrialMode, canAccessDatabase, isTrialCaseId } = useTrialMode();
  
  const [sections, setSections] = useState<CardSection[]>([
    { 
      id: '0', 
      title: 'Case Summary', 
      content: 'Provide a detailed factual summary of the incident, including dates, locations, parties involved, and the nature of damages or injuries.' 
    },
    { 
      id: '1', 
      title: 'INTRODUCTION', 
      content: '[This section will be auto-generated by AI]\n\nThe introduction identifies your client, the date and location of the incident, and establishes that the opposing party is liable.\n\nFormat: "This firm represents [Client Name] for injuries sustained in a collision on [Date] in [City, CA]. Based on the evidence, your insured, [Insured Name], is 100% liable for causing this collision."' 
    },
    { 
      id: '2', 
      title: 'FACTS', 
      content: '[This section will be auto-generated by AI]\n\nThe facts section details what happened: date, time, location, circumstances of the incident, weather/traffic conditions, witnesses, and police report information.\n\nThis section establishes the factual foundation for your liability and damages claims.' 
    },
    { 
      id: '3', 
      title: 'LIABILITY', 
      content: '[This section will be auto-generated by AI]\n\nThe liability section establishes legal responsibility by citing the opposing party\'s negligent conduct and applicable California law (e.g., Civil Code §1714, Vehicle Code sections).\n\nIt should address duty, breach, causation, and damages.' 
    },
    { 
      id: '4', 
      title: 'DAMAGES', 
      content: '[This section will be auto-generated by AI]\n\nThis section covers all damages:\n\n• INJURIES & MEDICAL TREATMENT: Describe your client\'s injuries, medical treatment received, healthcare providers, diagnostic tests, ongoing symptoms, and treatment timeline.\n\n• ECONOMIC DAMAGES: List all quantifiable financial losses including medical expenses (past and future), lost wages and earning capacity, property damage, and out-of-pocket costs.\n\n• NON-ECONOMIC DAMAGES: Describe intangible losses such as pain and suffering, emotional distress, loss of enjoyment of life, and impact on daily activities.' 
    },
    { 
      id: '5', 
      title: 'SETTLEMENT DEMAND', 
      content: '[This section will be auto-generated by AI]\n\nState the demand amount and deadline (typically 30 days). Include language about pursuing litigation if the demand is not met.\n\nFormat: "We hereby demand $[Amount] in full and final settlement of all claims..."' 
    },
    { 
      id: '6', 
      title: 'DOCUMENTATION PROVIDED', 
      content: '[This section will be auto-generated by AI]\n\nList all supporting documents enclosed:\n• Police Report\n• Photographs\n• Medical Records and Bills\n• Proof of Lost Wages\n• Physical Therapy Notes\n\nClick "Add Document" to add more items.' 
    },
  ]);
  const [draggedIndex, setDraggedIndex] = useState<number | null>(null);
  const [dragOverIndex, setDragOverIndex] = useState<number | null>(null);
  const [aiLoading, setAiLoading] = useState<string | null>(null);
  const [aiError, setAiError] = useState<string | null>(null);
  const [showPreview, setShowPreview] = useState(false);
  const [editingSection, setEditingSection] = useState<{id: string; title: string} | null>(null);
  const [currentCaseId, setCurrentCaseId] = useState<string | null>(null);
  const [currentCase, setCurrentCase] = useState<CaseFrontend | null>(null);
  const [saving, setSaving] = useState(false);
  const [saveSuccess, setSaveSuccess] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [userProfile, setUserProfile] = useState<UserProfile | null>(null);
  const [recipients, setRecipients] = useState<Recipient[]>([
    { id: '1', name: '', firm: '', address: '', phone: '', email: '' }
  ]);
  const [sendVia, setSendVia] = useState<SendViaOption>('Certified Mail');
  const [availableAttorneys, setAvailableAttorneys] = useState<Attorney[]>([]);
  const [selectedAttorneyIds, setSelectedAttorneyIds] = useState<Record<string, string>>({ '1': 'manual' });
  const [reInfo, setReInfo] = useState<REInfo>({
    caseName: '',
    dateOfLoss: '',
    caseNumber: '',
  });
  const [senderInfo, setSenderInfo] = useState<SenderInfo>({
    name: '',
    firm: '',
    address: '',
    phone: '',
    email: '',
  });
  const [hasGenerated, setHasGenerated] = useState(false);
  
  // Party identification for trial mode
  const [representationType, setRepresentationType] = useState<'plaintiff' | 'defendant'>('plaintiff');
  const [clientName, setClientName] = useState('');
  const [opposingPartyName, setOpposingPartyName] = useState('');

  const autoResizeTextarea = (textarea: HTMLTextAreaElement) => {
    textarea.style.height = 'auto';
    textarea.style.height = `${Math.max(192, textarea.scrollHeight)}px`; // min height of 192px (h-48)
  };

  // Handle attorney selection from dropdown for a specific recipient
  const handleAttorneySelect = (recipientId: string, attorneyId: string) => {
    setSelectedAttorneyIds(prev => ({ ...prev, [recipientId]: attorneyId }));
    
    if (attorneyId === 'manual') {
      // Clear fields for manual entry
      setRecipients(prev => prev.map(r => 
        r.id === recipientId 
          ? { ...r, name: '', firm: '', address: '', phone: '', email: '' }
          : r
      ));
      return;
    }
    
    const attorney = availableAttorneys.find(a => a.id === attorneyId);
    if (attorney) {
      setRecipients(prev => prev.map(r => 
        r.id === recipientId 
          ? { 
              ...r, 
              name: attorney.name || '', 
              firm: attorney.firm || '', 
              address: attorney.address || '', 
              phone: attorney.phone || '', 
              email: attorney.email || '' 
            }
          : r
      ));
    }
  };

  // Update a specific recipient field
  const updateRecipient = (recipientId: string, field: keyof Recipient, value: string) => {
    setRecipients(prev => prev.map(r => 
      r.id === recipientId ? { ...r, [field]: value } : r
    ));
  };

  // Add a new recipient
  const addRecipient = () => {
    const newId = Date.now().toString();
    setRecipients(prev => [...prev, { id: newId, name: '', firm: '', address: '', phone: '', email: '' }]);
    setSelectedAttorneyIds(prev => ({ ...prev, [newId]: 'manual' }));
  };

  // Remove a recipient
  const removeRecipient = (recipientId: string) => {
    if (recipients.length <= 1) return; // Keep at least one recipient
    setRecipients(prev => prev.filter(r => r.id !== recipientId));
    setSelectedAttorneyIds(prev => {
      const newIds = { ...prev };
      delete newIds[recipientId];
      return newIds;
    });
  };

  const updateSection = (id: string, field: 'title' | 'content', value: string) => {
    setSections(sections.map(section => 
      section.id === id ? { ...section, [field]: value } : section
    ));
  };

  const addSection = () => {
    setSections([...sections, { 
      id: Date.now().toString(), 
      title: `Section ${sections.length + 1}`, 
      content: '' 
    }]);
  };

  const removeSection = (id: string) => {
    setSections(sections.filter(section => section.id !== id));
  };

  // Reset to start a new letter (trial mode)
  const handleNewLetter = () => {
    setSections([
      { 
        id: '0', 
        title: 'Case Summary', 
        content: 'Provide a detailed factual summary of the incident, including dates, locations, parties involved, and the nature of damages or injuries.' 
      },
      { 
        id: '1', 
        title: 'INTRODUCTION', 
        content: '[This section will be auto-generated by AI]\n\nThe introduction identifies your client, the date and location of the incident, and establishes that the opposing party is liable.\n\nFormat: "This firm represents [Client Name] for injuries sustained in a collision on [Date] in [City, CA]. Based on the evidence, your insured, [Insured Name], is 100% liable for causing this collision."' 
      },
      { 
        id: '2', 
        title: 'FACTS', 
        content: '[This section will be auto-generated by AI]\n\nThe facts section details what happened: date, time, location, circumstances of the incident, weather/traffic conditions, witnesses, and police report information.\n\nThis section establishes the factual foundation for your liability and damages claims.' 
      },
      { 
        id: '3', 
        title: 'LIABILITY', 
        content: '[This section will be auto-generated by AI]\n\nThe liability section establishes legal responsibility by citing the opposing party\'s negligent conduct and applicable California law (e.g., Civil Code §1714, Vehicle Code sections).\n\nIt should address duty, breach, causation, and damages.' 
      },
      { 
        id: '4', 
        title: 'DAMAGES', 
        content: '[This section will be auto-generated by AI]\n\nThis section covers all damages:\n\n• INJURIES & MEDICAL TREATMENT: Describe your client\'s injuries, medical treatment received, healthcare providers, diagnostic tests, ongoing symptoms, and treatment timeline.\n\n• ECONOMIC DAMAGES: List all quantifiable financial losses including medical expenses (past and future), lost wages and earning capacity, property damage, and out-of-pocket costs.\n\n• NON-ECONOMIC DAMAGES: Describe intangible losses such as pain and suffering, emotional distress, loss of enjoyment of life, and impact on daily activities.' 
      },
      { 
        id: '5', 
        title: 'SETTLEMENT DEMAND', 
        content: '[This section will be auto-generated by AI]\n\nState the demand amount and deadline (typically 30 days). Include language about pursuing litigation if the demand is not met.\n\nFormat: "We hereby demand $[Amount] in full and final settlement of all claims..."' 
      },
      { 
        id: '6', 
        title: 'DOCUMENTATION PROVIDED', 
        content: '[This section will be auto-generated by AI]\n\nList all supporting documents enclosed:\n• Police Report\n• Photographs\n• Medical Records and Bills\n• Proof of Lost Wages\n• Physical Therapy Notes\n\nClick "Add Document" to add more items.' 
      },
    ]);
    // Reset other form fields
    setSenderInfo({ name: '', firm: '', address: '', phone: '', email: '' });
    setRecipients([{ id: '1', name: '', firm: '', address: '', phone: '', email: '' }]);
    setSelectedAttorneyIds({ '1': 'manual' });
    setReInfo({ caseName: '', dateOfLoss: '', caseNumber: '' });
    setSendVia('Certified Mail');
    setHasGenerated(false);
  };

  const addDocument = (sectionId: string) => {
    const section = sections.find(s => s.id === sectionId);
    if (!section) return;
    
    const currentContent = section.content.trim();
    const newDocument = '\n\n[New Document]';
    const updatedContent = currentContent + newDocument;
    
    updateSection(sectionId, 'content', updatedContent);
  };

  const handleAIAssist = async (sectionId: string) => {
    // Only allow for Case Summary and Introduction sections
    if (sectionId !== '0' && sectionId !== '1') {
      setAiError('AI assist is only available for Case Summary and Introduction sections');
      setTimeout(() => setAiError(null), 5000);
      return;
    }

    setAiLoading(sectionId);
    setAiError(null);

    try {
      const section = sections.find(s => s.id === sectionId);
      if (!section) return;

      let apiEndpoint = '/api/ai';
      
      // Case Summary uses populate-sections endpoint to fill all sections
      if (sectionId === '0') {
        apiEndpoint = '/api/ai/populate-sections';
      }

      const requestBody = sectionId === '0' 
        ? { 
            caseDescription: section.content,
            allSections: sections,
            // Include explicit party info for trial mode
            partyInfo: isTrialMode && clientName ? {
              representationType,
              clientName: clientName.trim(),
              opposingPartyName: opposingPartyName.trim()
            } : undefined
          }
        : {
            sectionId,
            sectionTitle: section.title,
            currentContent: section.content,
            allSections: sections,
          };

      const response = await fetch(apiEndpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(requestBody),
      });

      if (!response.ok) {
        // Check if response is JSON
        const contentType = response.headers.get('content-type');
        let errorData;
        
        if (contentType && contentType.includes('application/json')) {
          errorData = await response.json();
        } else {
          // Response is HTML (error page), get text instead
          const text = await response.text();
          console.error('Non-JSON error response:', text.substring(0, 200));
          throw new Error(`Server error: ${response.status} ${response.statusText}. Please check your API configuration.`);
        }
        
        const errorMessage = errorData.error || 
                             errorData.details?.error?.message ||
                             `Server error: ${response.status} ${response.statusText}`;
        
        throw new Error(errorMessage);
      }

      const data = await response.json();
      
      // If Case Summary, update all sections
      if (sectionId === '0' && data.sections) {
        // Update each section with generated content
        setSections(prevSections => 
          prevSections.map(sec => {
            if (data.sections[sec.id]) {
              return { ...sec, content: data.sections[sec.id] };
            }
            return sec;
          })
        );
        // Mark as generated for trial mode UI
        setHasGenerated(true);
      } else {
        // Single section update (Introduction)
        updateSection(sectionId, 'content', data.content);
      }
    } catch (error) {
      console.error('AI Assist error:', error);
      setAiError(error instanceof Error ? error.message : 'An error occurred');
      setTimeout(() => setAiError(null), 5000);
    } finally {
      setAiLoading(null);
    }
  };

  const handleDragStart = (index: number) => {
    setDraggedIndex(index);
  };

  const handleDragOver = (e: React.DragEvent, index: number) => {
    e.preventDefault();
    setDragOverIndex(index);
  };

  const handleDragLeave = () => {
    setDragOverIndex(null);
  };

  const handleDrop = (e: React.DragEvent, dropIndex: number) => {
    e.preventDefault();
    
    if (draggedIndex === null || draggedIndex === dropIndex) {
      setDraggedIndex(null);
      setDragOverIndex(null);
      return;
    }

    // Prevent dropping Case Summary (id: '0') or dropping before Case Summary
    const draggedSection = sections[draggedIndex];
    if (draggedSection.id === '0' || dropIndex === 0) {
      setDraggedIndex(null);
      setDragOverIndex(null);
      return;
    }

    const newSections = [...sections];
    
    // Remove the dragged item
    newSections.splice(draggedIndex, 1);
    
    // Insert at new position (but never at index 0)
    newSections.splice(dropIndex, 0, draggedSection);
    
    setSections(newSections);
    setDraggedIndex(null);
    setDragOverIndex(null);
  };

  const handleDragEnd = () => {
    setDraggedIndex(null);
    setDragOverIndex(null);
  };

  // Auto-resize textareas when sections change
  useEffect(() => {
    const textareas = document.querySelectorAll('textarea');
    textareas.forEach((textarea) => {
      autoResizeTextarea(textarea as HTMLTextAreaElement);
    });
  }, [sections]);

  // Load user profile for letterhead info (only for authenticated users)
  useEffect(() => {
    // Skip profile loading in trial mode - no user to load
    if (isTrialMode) return;
    
    const loadUserProfile = async () => {
      try {
        const profile = await userProfileStorage.getProfile();
        if (profile) {
          setUserProfile(profile);
        }
      } catch (error) {
        console.error('Error loading user profile:', error);
      }
    };
    loadUserProfile();
  }, [isTrialMode]);

  // Auto-populate sender info from user profile for logged-in users
  useEffect(() => {
    if (!isTrialMode && userProfile) {
      setSenderInfo({
        name: userProfile.fullName || '',
        firm: userProfile.firmName || '',
        address: userProfile.firmAddress || '',
        phone: userProfile.firmPhone || '',
        email: userProfile.firmEmail || '',
      });
    }
  }, [isTrialMode, userProfile]);

  // Load case data from caseId if provided
  useEffect(() => {
    const loadCase = async () => {
      const caseId = searchParams?.get('caseId');
      
      // SECURITY: Block real case IDs in trial mode
      if (caseId && isTrialMode && !isTrialCaseId(caseId)) {
        console.warn('[SECURITY] Attempted to access real case ID in trial mode - blocked');
        return;
      }
      
      if (caseId && !isTrialMode && canAccessDatabase()) {
        // SECURITY: Validate UUID format before database operations
        if (!UUID_REGEX.test(caseId)) {
          console.warn('[SECURITY] Invalid case ID format - blocked');
          return;
        }
        
        const supabase = createClient();
        const { data: { user } } = await supabase.auth.getUser();
        
        if (user) {
          const foundCase = await supabaseCaseStorage.getCase(caseId);
          if (foundCase) {
            console.log(`[AUDIT] Demand letter page accessed for case: ${caseId}`);
            setCurrentCaseId(caseId);
            setCurrentCase(foundCase);
            
            // Load saved demand letter sections if they exist
            if (foundCase.demandLetterSections && foundCase.demandLetterSections.length > 0) {
              setSections(foundCase.demandLetterSections);
            } else if (foundCase.facts) {
              // No saved sections but have facts - populate case description only, clear others
              setSections(prevSections =>
                prevSections.map(section =>
                  section.id === '0'
                    ? { ...section, content: foundCase.facts || '' }
                    : { ...section, content: '' }
                )
              );
            }
            
            // Collect all attorneys from all defendants
            const allAttorneys: Attorney[] = [];
            foundCase.defendants?.forEach(defendant => {
              if (defendant.attorneys) {
                allAttorneys.push(...defendant.attorneys);
              }
            });
            setAvailableAttorneys(allAttorneys);
            
            // Auto-select first attorney if available
            const firstAttorney = allAttorneys[0];
            if (firstAttorney) {
              setSelectedAttorneyIds({ '1': firstAttorney.id });
              setRecipients([{
                id: '1',
                name: firstAttorney.name || '',
                firm: firstAttorney.firm || '',
                address: firstAttorney.address || '',
                phone: firstAttorney.phone || '',
                email: firstAttorney.email || '',
              }]);
            }
            
            // Populate RE: section info from case
            setReInfo({
              caseName: foundCase.caseName || '',
              dateOfLoss: '', // User will need to enter this
              caseNumber: foundCase.caseNumber || '',
            });
          }
        }
      }
    };
    
    loadCase();
  }, [searchParams, isTrialMode, canAccessDatabase, isTrialCaseId]);

  // Save draft - secure implementation with no data leakage
  const handleSaveDraft = async () => {
    // SECURITY: Require a valid case ID
    if (!currentCaseId) {
      setSaveError('No case selected. Please access this page from the case dashboard.');
      setTimeout(() => setSaveError(null), 5000);
      return;
    }

    // SECURITY: Validate UUID format to prevent injection
    if (!UUID_REGEX.test(currentCaseId)) {
      console.warn('[SECURITY] Attempted to save with invalid case ID format - blocked');
      setSaveError('Invalid case ID. Cannot save to database.');
      setTimeout(() => setSaveError(null), 5000);
      return;
    }

    // SECURITY: Block saves in trial mode
    if (isTrialMode) {
      setSaveError('Saving is disabled in trial mode.');
      setTimeout(() => setSaveError(null), 5000);
      return;
    }

    setSaving(true);
    setSaveSuccess(false);
    setSaveError(null);

    try {
      // SECURITY: supabaseCaseStorage.updateCase uses Row Level Security
      // which ensures user can only update their own cases
      const result = await supabaseCaseStorage.updateCase(currentCaseId, {
        demandLetterSections: sections,
      });

      if (result) {
        setSaveSuccess(true);
        console.log(`[AUDIT] Demand letter draft saved for case: ${currentCaseId}`);
        setTimeout(() => setSaveSuccess(false), 3000);
      } else {
        setSaveError('Failed to save draft. Please try again.');
        setTimeout(() => setSaveError(null), 5000);
      }
    } catch (error) {
      console.error('Error saving draft:', error);
      setSaveError('An error occurred while saving. Please try again.');
      setTimeout(() => setSaveError(null), 5000);
    } finally {
      setSaving(false);
    }
  };

  // Split sections into Case Summary and other sections
  const caseDescription = sections.find(s => s.id === '0');
  const otherSections = sections.filter(s => s.id !== '0');

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-blue-50">
      <Header />
      <TrialModeBanner />
      
      {/* Case Name Header - Only show when accessed from case dashboard */}
      {currentCase && !isTrialMode && searchParams?.get('caseId') && (
        <div className="bg-gradient-to-r from-blue-600 to-blue-700 text-white py-4 shadow-md">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-3">
                <Link 
                  href={`/dashboard/cases/${currentCase.id}`}
                  className="hover:opacity-80 transition-opacity"
                >
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                  </svg>
                </Link>
                <div>
                  <h2 className="text-xl font-bold">{currentCase.caseName}</h2>
                  {currentCase.caseNumber && (
                    <p className="text-sm text-blue-100">Case #: {currentCase.caseNumber}</p>
                  )}
                </div>
              </div>
              <Link
                href={`/dashboard/cases/${currentCase.id}`}
                className="text-sm hover:underline text-blue-100"
              >
                Back to Case
              </Link>
            </div>
          </div>
        </div>
      )}

      {/* Hero Section */}
      <section className="bg-gradient-to-br from-blue-50 via-white to-blue-50 pt-16 pb-8">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-4xl mx-auto">
            <h1 className="text-5xl md:text-6xl font-bold mb-8 leading-tight">
              <span className="gradient-text">Demand Letter</span> <span className="text-gray-900">Generator</span>
            </h1>
            <p className="text-xl md:text-2xl text-slate-600 mb-12 leading-relaxed">
              Create professional demand letters with AI-powered content generation and proper legal formatting.
            </p>
          </div>
        </div>
      </section>

      <div className="min-h-screen p-6 bg-gradient-to-br from-blue-50 via-white to-blue-50">
        <div className="max-w-7xl mx-auto">
          {/* Sending Attorney Card - Show for logged-in users (pre-populated) or trial mode after generation */}
          {((!isTrialMode && userProfile) || (isTrialMode && hasGenerated)) && (
            <div className="mb-8">
              <div className="glass-strong p-6 rounded-2xl hover:shadow-2xl transition-all duration-300">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-3">
                    <div className="text-blue-600">
                      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                      </svg>
                    </div>
                    <div>
                      <h2 className="text-xl font-semibold text-gray-900">
                        {isTrialMode ? 'Sending Attorney Information' : 'Your Firm Information'}
                      </h2>
                      {!isTrialMode && (
                        <p className="text-sm text-gray-500">
                          Pre-populated from your profile. <Link href="/settings" className="text-blue-600 hover:underline">Update in settings</Link>
                        </p>
                      )}
                    </div>
                  </div>
                </div>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {/* Attorney Name */}
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Attorney Name</label>
                    <input
                      type="text"
                      value={senderInfo.name}
                      onChange={(e) => setSenderInfo(prev => ({ ...prev, name: e.target.value }))}
                      className="w-full px-4 py-2 bg-white border border-gray-200 rounded-xl text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      placeholder="Your name"
                    />
                  </div>
                  
                  {/* Law Firm */}
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Law Firm</label>
                    <input
                      type="text"
                      value={senderInfo.firm}
                      onChange={(e) => setSenderInfo(prev => ({ ...prev, firm: e.target.value }))}
                      className="w-full px-4 py-2 bg-white border border-gray-200 rounded-xl text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      placeholder="Law firm name"
                    />
                  </div>
                  
                  {/* Address */}
                  <div className="md:col-span-2">
                    <label className="block text-sm font-medium text-gray-700 mb-1">Address</label>
                    <input
                      type="text"
                      value={senderInfo.address}
                      onChange={(e) => setSenderInfo(prev => ({ ...prev, address: e.target.value }))}
                      className="w-full px-4 py-2 bg-white border border-gray-200 rounded-xl text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      placeholder="Street address, City, State ZIP"
                    />
                  </div>
                  
                  {/* Phone */}
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Phone</label>
                    <input
                      type="tel"
                      value={senderInfo.phone}
                      onChange={(e) => setSenderInfo(prev => ({ ...prev, phone: e.target.value }))}
                      className="w-full px-4 py-2 bg-white border border-gray-200 rounded-xl text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      placeholder="(555) 555-5555"
                    />
                  </div>
                  
                  {/* Email */}
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Email</label>
                    <input
                      type="email"
                      value={senderInfo.email}
                      onChange={(e) => setSenderInfo(prev => ({ ...prev, email: e.target.value }))}
                      className="w-full px-4 py-2 bg-white border border-gray-200 rounded-xl text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      placeholder="attorney@lawfirm.com"
                    />
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Recipient Card - Who the demand letter is sent to */}
          {(!isTrialMode || hasGenerated) && (
          <div className="mb-8">
            <div className="glass-strong p-6 rounded-2xl hover:shadow-2xl transition-all duration-300">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-3">
                  <div className="text-blue-600">
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                    </svg>
                  </div>
                  <h2 className="text-xl font-semibold text-gray-900">Recipient Information</h2>
                </div>
                <button
                  onClick={addRecipient}
                  className="flex items-center gap-1 px-3 py-1.5 text-sm font-medium text-blue-600 bg-blue-50 rounded-lg hover:bg-blue-100 transition-colors"
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                  </svg>
                  Add Recipient
                </button>
              </div>
              
              {/* Send Via - Applies to all recipients */}
              <div className="mb-4">
                <label className="block text-sm font-medium text-gray-700 mb-1">Send Via</label>
                <select
                  value={sendVia}
                  onChange={(e) => setSendVia(e.target.value as SendViaOption)}
                  className="w-full md:w-1/2 px-4 py-2 bg-white border border-gray-200 rounded-xl text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                >
                  <option value="Certified Mail">Certified Mail, Return Receipt Requested</option>
                  <option value="Email">Email</option>
                  <option value="Regular Mail">Regular Mail</option>
                  <option value="Fax">Fax</option>
                  <option value="Hand Delivery">Hand Delivery</option>
                </select>
              </div>

              {/* Recipients List */}
              <div className="space-y-4">
                {recipients.map((recipient, index) => (
                  <div key={recipient.id} className="p-4 bg-gray-50 rounded-xl border border-gray-200">
                    <div className="flex items-center justify-between mb-3">
                      <span className="text-sm font-medium text-gray-600">Recipient {index + 1}</span>
                      {recipients.length > 1 && (
                        <button
                          onClick={() => removeRecipient(recipient.id)}
                          className="text-red-500 hover:text-red-700 p-1 hover:bg-red-50 rounded transition-colors"
                          title="Remove recipient"
                        >
                          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                          </svg>
                        </button>
                      )}
                    </div>
                    
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                      {/* Recipient - Dropdown with attorneys from case */}
                      <div>
                        <label className="block text-xs font-medium text-gray-600 mb-1">
                          {availableAttorneys.length > 0 ? 'Select Recipient' : 'Recipient Name'}
                        </label>
                        {availableAttorneys.length > 0 ? (
                          <select
                            value={selectedAttorneyIds[recipient.id] || 'manual'}
                            onChange={(e) => handleAttorneySelect(recipient.id, e.target.value)}
                            className="w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-lg text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                          >
                            <option value="manual">-- Enter Manually --</option>
                            {availableAttorneys.map(attorney => (
                              <option key={attorney.id} value={attorney.id}>
                                {attorney.name}{attorney.firm ? ` (${attorney.firm})` : ''}
                              </option>
                            ))}
                          </select>
                        ) : (
                          <input
                            type="text"
                            value={recipient.name}
                            onChange={(e) => updateRecipient(recipient.id, 'name', e.target.value)}
                            className="w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-lg text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                            placeholder="Attorney Name"
                          />
                        )}
                      </div>
                      
                      {/* Recipient Name - Show when manual entry is selected */}
                      {availableAttorneys.length > 0 && selectedAttorneyIds[recipient.id] === 'manual' && (
                        <div>
                          <label className="block text-xs font-medium text-gray-600 mb-1">Recipient Name</label>
                          <input
                            type="text"
                            value={recipient.name}
                            onChange={(e) => updateRecipient(recipient.id, 'name', e.target.value)}
                            className="w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-lg text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                            placeholder="Attorney Name"
                          />
                        </div>
                      )}
                      
                      {/* Law Firm / Company */}
                      <div>
                        <label className="block text-xs font-medium text-gray-600 mb-1">Law Firm / Company</label>
                        <input
                          type="text"
                          value={recipient.firm}
                          onChange={(e) => updateRecipient(recipient.id, 'firm', e.target.value)}
                          className="w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-lg text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                          placeholder="Law Firm or Insurance Company"
                        />
                      </div>
                      
                      {/* Address */}
                      <div className="md:col-span-2">
                        <label className="block text-xs font-medium text-gray-600 mb-1">Address</label>
                        <input
                          type="text"
                          value={recipient.address}
                          onChange={(e) => updateRecipient(recipient.id, 'address', e.target.value)}
                          className="w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-lg text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                          placeholder="Street Address, City, State ZIP"
                        />
                      </div>
                      
                      {/* Phone */}
                      <div>
                        <label className="block text-xs font-medium text-gray-600 mb-1">Phone</label>
                        <input
                          type="text"
                          value={recipient.phone}
                          onChange={(e) => updateRecipient(recipient.id, 'phone', e.target.value)}
                          className="w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-lg text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                          placeholder="(555) 555-5555"
                        />
                      </div>
                      
                      {/* Email */}
                      <div>
                        <label className="block text-xs font-medium text-gray-600 mb-1">Email</label>
                        <input
                          type="email"
                          value={recipient.email}
                          onChange={(e) => updateRecipient(recipient.id, 'email', e.target.value)}
                          className="w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-lg text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                          placeholder="email@lawfirm.com"
                        />
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
          )}

          {/* RE: Section Card */}
          {(!isTrialMode || hasGenerated) && (
          <div className="mb-8">
            <div className="glass-strong p-6 rounded-2xl hover:shadow-2xl transition-all duration-300">
              <div className="flex items-center gap-3 mb-4">
                <div className="text-blue-600">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                </div>
                <h2 className="text-xl font-semibold text-gray-900">RE: Section</h2>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Confidential Label */}
                <div className="md:col-span-2">
                  <div className="px-4 py-2 bg-blue-50 border border-blue-200 rounded-xl">
                    <span className="text-sm font-semibold text-blue-700">CONFIDENTIAL DEMAND LETTER</span>
                  </div>
                </div>
                
                {/* Case Name */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Case Name</label>
                  <input
                    type="text"
                    value={reInfo.caseName}
                    onChange={(e) => setReInfo(prev => ({ ...prev, caseName: e.target.value }))}
                    className="w-full px-4 py-2 bg-white border border-gray-200 rounded-xl text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    placeholder="e.g., Smith v. Jones"
                  />
                </div>
                
                {/* Date of Loss */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Date of Loss</label>
                  <input
                    type="date"
                    value={reInfo.dateOfLoss}
                    onChange={(e) => setReInfo(prev => ({ ...prev, dateOfLoss: e.target.value }))}
                    className="w-full px-4 py-2 bg-white border border-gray-200 rounded-xl text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  />
                </div>
                
                {/* Case Number */}
                <div className="md:col-span-2">
                  <label className="block text-sm font-medium text-gray-700 mb-1">Case/Claim Number</label>
                  <input
                    type="text"
                    value={reInfo.caseNumber}
                    onChange={(e) => setReInfo(prev => ({ ...prev, caseNumber: e.target.value }))}
                    className="w-full px-4 py-2 bg-white border border-gray-200 rounded-xl text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    placeholder="Case number or claim number"
                  />
                </div>
              </div>
            </div>
          </div>
          )}

          {/* Party Information Section - Trial Mode Only */}
          {isTrialMode && (
            <div className="mb-8">
              <div className="glass-strong p-6 rounded-2xl">
                <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
                  <svg className="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
                  </svg>
                  Party Information
                </h3>
                
                {/* Representation Type */}
                <div className="mb-4">
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    You Represent:
                  </label>
                  <div className="flex gap-4">
                    <label className="flex items-center gap-2 cursor-pointer">
                      <input
                        type="radio"
                        name="representationType"
                        value="plaintiff"
                        checked={representationType === 'plaintiff'}
                        onChange={() => setRepresentationType('plaintiff')}
                        className="w-4 h-4 text-blue-600 focus:ring-blue-500"
                      />
                      <span className="text-gray-700">Plaintiff / Claimant</span>
                    </label>
                    <label className="flex items-center gap-2 cursor-pointer">
                      <input
                        type="radio"
                        name="representationType"
                        value="defendant"
                        checked={representationType === 'defendant'}
                        onChange={() => setRepresentationType('defendant')}
                        className="w-4 h-4 text-blue-600 focus:ring-blue-500"
                      />
                      <span className="text-gray-700">Defendant / Respondent</span>
                    </label>
                  </div>
                </div>
                
                {/* Party Names */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      {representationType === 'plaintiff' ? 'Your Client (Plaintiff)' : 'Your Client (Defendant)'}
                    </label>
                    <input
                      type="text"
                      value={clientName}
                      onChange={(e) => setClientName(e.target.value)}
                      placeholder={representationType === 'plaintiff' ? 'e.g., John Smith' : 'e.g., ABC Company, LLC'}
                      className="w-full px-4 py-2 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-900 placeholder-gray-400"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      {representationType === 'plaintiff' ? 'Opposing Party (Defendant)' : 'Opposing Party (Plaintiff)'}
                    </label>
                    <input
                      type="text"
                      value={opposingPartyName}
                      onChange={(e) => setOpposingPartyName(e.target.value)}
                      placeholder={representationType === 'plaintiff' ? 'e.g., XYZ Corporation, Inc.' : 'e.g., Jane Doe'}
                      className="w-full px-4 py-2 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-900 placeholder-gray-400"
                    />
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Case Summary Section - Separate at Top */}
          {caseDescription && (
            <div className="mb-8">
              <div className="glass-strong p-6 rounded-2xl hover:shadow-2xl transition-all duration-300 relative">
                <div className="flex justify-between items-start mb-4 gap-3">
                  <div className="text-gray-400 flex items-center pt-1">
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                  </div>
                  <input
                    type="text"
                    value={caseDescription.title}
                    onChange={(e) => updateSection(caseDescription.id, 'title', e.target.value)}
                    className="text-xl font-semibold text-gray-900 bg-transparent border-none outline-none flex-1 placeholder-gray-400"
                    placeholder="Section Title"
                  />
                </div>
                <div className="relative">
                  <textarea
                    value={caseDescription.content}
                    onChange={(e) => {
                      updateSection(caseDescription.id, 'content', e.target.value);
                      autoResizeTextarea(e.target as HTMLTextAreaElement);
                    }}
                    onInput={(e) => autoResizeTextarea(e.target as HTMLTextAreaElement)}
                    ref={(textarea) => {
                      if (textarea) {
                        autoResizeTextarea(textarea);
                      }
                    }}
                    className="w-full min-h-48 p-4 bg-white border border-gray-200 rounded-xl text-gray-900 placeholder-gray-400 resize-none focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 overflow-hidden"
                    placeholder="Enter section content here... (Template will be added later)"
                  />
                </div>
                {aiError && (
                  <div className="mt-2 text-sm text-red-600 bg-red-50 p-2 rounded border border-red-200">
                    {aiError}
                  </div>
                )}
              </div>
            </div>
          )}

          {/* AI Generation Button - Show after Case Summary for both trial mode and logged-in users */}
          {caseDescription && (
            <button
              onClick={() => handleAIAssist('0')}
              disabled={aiLoading === '0' || !caseDescription.content.trim() || caseDescription.content.length < 50}
              className="w-full mb-8 py-4 px-6 bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white rounded-xl font-semibold transition-all duration-300 flex items-center justify-center space-x-2 disabled:opacity-50 disabled:cursor-not-allowed shadow-lg hover:shadow-xl"
            >
              {aiLoading === '0' ? (
                <>
                  <svg className="w-5 h-5 animate-spin text-white" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                  <span>Generating Demand Letter...</span>
                </>
              ) : (
                <>
                  <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
                  </svg>
                  <span>Generate AI-Powered Demand Letter</span>
                </>
              )}
            </button>
          )}

          {/* Divider and Demand Letter Sections - Hidden until generated in trial mode */}
          {(!isTrialMode || hasGenerated) && (
          <>
          {/* Divider */}
          <div className="mb-8 flex items-center gap-4">
            <div className="flex-1 h-px bg-gradient-to-r from-transparent via-blue-200 to-transparent"></div>
            <span className="text-gray-600 text-sm font-medium">Demand Letter Sections</span>
            <div className="flex-1 h-px bg-gradient-to-r from-transparent via-blue-200 to-transparent"></div>
          </div>

          {/* Other Cards Stack */}
          <div className="flex flex-col gap-6 mb-8">
            {otherSections.map((section) => {
              // Find original index for drag/drop
              const originalIndex = sections.findIndex(s => s.id === section.id);
              return (
                <div
                  key={section.id}
                  draggable
                  onDragStart={() => handleDragStart(originalIndex)}
                  onDragOver={(e) => handleDragOver(e, originalIndex)}
                  onDragLeave={handleDragLeave}
                  onDrop={(e) => handleDrop(e, originalIndex)}
                  onDragEnd={handleDragEnd}
                  className={`glass-strong p-6 rounded-2xl hover:shadow-2xl transition-all duration-300 relative cursor-move ${
                    draggedIndex === originalIndex ? 'opacity-50 scale-95' : ''
                  } ${
                    dragOverIndex === originalIndex && draggedIndex !== originalIndex ? 'border-2 border-blue-500 border-dashed scale-105' : ''
                  }`}
                >
                  <div className="flex justify-between items-start mb-4 gap-3">
                    {/* Drag Handle */}
                    <div className="text-gray-400 hover:text-gray-600 transition-colors flex items-center pt-1">
                      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 8h16M4 16h16" />
                      </svg>
                    </div>
                    <input
                      type="text"
                      value={section.title}
                      onChange={(e) => updateSection(section.id, 'title', e.target.value)}
                      className="text-xl font-semibold text-gray-900 bg-transparent border-none outline-none flex-1 placeholder-gray-400"
                      placeholder="Section Title"
                    />
                    {sections.length > 1 && (
                      <button
                        onClick={() => removeSection(section.id)}
                        className="text-gray-400 hover:text-red-600 transition-colors p-1"
                        aria-label="Remove section"
                      >
                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                      </button>
                    )}
                  </div>
                  <div className="relative">
                    <textarea
                      value={section.content}
                      onChange={(e) => {
                        updateSection(section.id, 'content', e.target.value);
                        autoResizeTextarea(e.target as HTMLTextAreaElement);
                      }}
                      onInput={(e) => autoResizeTextarea(e.target as HTMLTextAreaElement)}
                      ref={(textarea) => {
                        if (textarea) {
                          autoResizeTextarea(textarea);
                        }
                      }}
                      className="w-full min-h-48 p-4 pr-14 bg-white border border-gray-200 rounded-xl text-gray-900 placeholder-gray-400 resize-none focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 overflow-hidden"
                      placeholder="Enter section content here..."
                    />
                    {/* AI Sparkle Button - Opens AI Edit Chat */}
                    <button
                      onClick={() => setEditingSection({ id: section.id, title: section.title })}
                      className="absolute bottom-3 right-3 p-2.5 bg-gradient-to-br from-blue-600 to-blue-800 rounded-full shadow-lg hover:shadow-xl hover:scale-110 transition-all duration-300 group"
                      aria-label="Edit with AI"
                      title="Edit with AI Assistant"
                    >
                        <svg 
                          className="w-4 h-4 text-white group-hover:rotate-12 transition-transform duration-300" 
                          fill="currentColor" 
                          viewBox="0 0 24 24"
                        >
                          <path d="M12 0L13.5 8.5L22 10L13.5 11.5L12 20L10.5 11.5L2 10L10.5 8.5L12 0Z" />
                          <path d="M6 4L6.5 6.5L9 7L6.5 7.5L6 10L5.5 7.5L3 7L5.5 6.5L6 4Z" />
                          <path d="M18 14L18.5 16.5L21 17L18.5 17.5L18 20L17.5 17.5L15 17L17.5 16.5L18 14Z" />
                        </svg>
                    </button>
                  </div>
                  {aiError && section.id === '1' && (
                    <div className="mt-2 text-sm text-red-600 bg-red-50 p-2 rounded border border-red-200">
                      {aiError}
                    </div>
                  )}
                  {/* Add Document Button - Only for DOCUMENTATION PROVIDED section */}
                  {section.id === '8' && (
                    <div className="mt-4 flex justify-end">
                      <button
                        onClick={() => addDocument(section.id)}
                        className="px-4 py-2 bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white rounded-full text-sm font-semibold transition-all duration-300 shadow-lg hover:shadow-xl flex items-center gap-2"
                      >
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                        </svg>
                        Add Document
                      </button>
                    </div>
                  )}
                </div>
              );
            })}
          </div>

          {/* Add Section Button */}
          <div className="mb-8 flex justify-center">
            <button
              onClick={addSection}
              className="px-6 py-3 bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white rounded-full font-semibold transition-all duration-300 shadow-lg hover:shadow-xl"
            >
              + Add Section
            </button>
          </div>

          {/* Action Buttons */}
          <div className="glass p-6 rounded-2xl flex flex-col gap-4">
            {/* Error message stays as banner */}
            {saveError && (
              <div className="text-sm text-red-600 bg-red-50 p-3 rounded-lg border border-red-200 flex items-center gap-2">
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
                {saveError}
              </div>
            )}
            
            <div className="flex gap-4 justify-end items-center">
              {!isTrialMode && (
                <button 
                  onClick={handleSaveDraft}
                  disabled={saving || !currentCaseId}
                  className={`px-6 py-3 rounded-full font-semibold transition-all duration-300 flex items-center gap-2 ${
                    saving ? 'opacity-50 cursor-not-allowed' : ''
                  } ${!currentCaseId 
                    ? 'opacity-50 cursor-not-allowed bg-gray-100 text-gray-400 border border-gray-200' 
                    : saveSuccess 
                      ? 'bg-green-600 text-white'
                      : 'bg-white border border-gray-300 text-gray-700 hover:bg-gray-50'
                  }`}
                  title={!currentCaseId ? 'Access from case dashboard to enable saving' : 'Save draft to case'}
                >
                  {saving ? (
                    <>
                      <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                      </svg>
                      <span>Saving...</span>
                    </>
                  ) : saveSuccess ? (
                    <>
                      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                      </svg>
                      <span>Saved!</span>
                    </>
                  ) : (
                    <>
                      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4" />
                      </svg>
                      <span>Save Draft</span>
                    </>
                  )}
                </button>
              )}
              {/* New Letter Button */}
              <button
                onClick={handleNewLetter}
                className="px-6 py-3 bg-white border border-gray-300 text-gray-700 rounded-full font-semibold hover:bg-gray-50 transition-all duration-300 flex items-center gap-2"
              >
                <RotateCcw className="w-4 h-4" />
                <span>New Letter</span>
              </button>
              <button 
                onClick={() => setShowPreview(true)}
                className="px-6 py-3 bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white rounded-full font-semibold transition-all duration-300 shadow-lg hover:shadow-xl"
              >
              Preview Letter
            </button>
            </div>
          </div>
          </>
          )}

          {/* Legal Disclaimer */}
          <div className="glass p-6 rounded-2xl bg-amber-50 border border-amber-200 mt-6">
            <h4 className="font-medium text-amber-800 mb-2">⚠️ Legal Disclaimer</h4>
            <p className="text-amber-800 text-sm">
              This document is AI-generated and should be reviewed by a qualified attorney before sending. 
              The content may require modifications to meet specific jurisdictional requirements and 
              case-specific details. Always consult with legal counsel for proper legal advice.
            </p>
          </div>
        </div>
      </div>
      
      <Footer />

      {/* Preview Modal */}
      <PreviewModal
        isOpen={showPreview}
        onClose={() => setShowPreview(false)}
        sections={sections}
        caseInfo={{
          attorneyName: isTrialMode ? senderInfo.name || undefined : userProfile?.fullName || undefined,
          lawFirmName: isTrialMode ? senderInfo.firm || undefined : userProfile?.firmName || undefined,
          stateBarNumber: isTrialMode ? undefined : userProfile?.barNumber || undefined,
          address: isTrialMode ? senderInfo.address || undefined : userProfile?.firmAddress || undefined,
          phone: isTrialMode ? senderInfo.phone || undefined : userProfile?.firmPhone || undefined,
          email: isTrialMode ? senderInfo.email || undefined : userProfile?.firmEmail || undefined,
        }}
        recipients={recipients}
        sendVia={sendVia}
        reInfo={reInfo}
      />

      {/* AI Edit Chat Modal */}
      {editingSection && (
        <AIEditChatModal
          isOpen={!!editingSection}
          onClose={() => setEditingSection(null)}
          sectionId={editingSection.id}
          sectionTitle={editingSection.title}
          currentContent={sections.find(s => s.id === editingSection.id)?.content || ''}
          caseDescription={sections.find(s => s.id === '0')?.content || ''}
          caseId={currentCaseId || ''}
          onApplyEdit={(newContent) => {
            updateSection(editingSection.id, 'content', newContent);
            setEditingSection(null);
          }}
          isTrialMode={isTrialMode}
        />
      )}
    </div>
  );
}





