'use client';

import { useState, useRef, useEffect, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import TrialModeBanner from '@/components/TrialModeBanner';
import PreviewModal from './components/PreviewModal';
import AIEditChatModal from './components/AIEditChatModal';
import { supabaseCaseStorage, CaseFrontend } from '@/lib/supabase/caseStorage';
import { createClient } from '@/lib/supabase/client';
import { useTrialMode } from '@/lib/contexts/TrialModeContext';
import { userProfileStorage, UserProfile } from '@/lib/supabase/userProfileStorage';
import { RotateCcw } from 'lucide-react';

interface CardSection {
  id: string;
  title: string;
  content: string;
}

interface ReportInfo {
  caseName: string;
  caseNumber: string;
  reportDate: string;
  preparedBy: string;
  preparedFor: string;
}

// UUID regex for security validation
const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export default function StatusReportPage() {
  return (
    <Suspense
      fallback={
        <div className="min-h-screen bg-white">
          <Header />
          <div className="p-6 text-gray-600">Loading status report generator...</div>
          <Footer />
        </div>
      }
    >
      <StatusReportPageContent />
    </Suspense>
  );
}

function StatusReportPageContent() {
  const searchParams = useSearchParams();
  const { isTrialMode, canAccessDatabase, isTrialCaseId } = useTrialMode();
  
  const [sections, setSections] = useState<CardSection[]>([
    { 
      id: '0', 
      title: 'Case Summary', 
      content: 'Provide a comprehensive summary of the case including key facts, parties involved, claims, and current status. This will be used to generate the status report sections.' 
    },
    { 
      id: '1', 
      title: 'FACTUAL BACKGROUND', 
      content: '[This section will be auto-generated by AI]\n\nDescribe the key facts of the case, including the incident date, parties, what occurred, and how liability arose. Include relevant details that support your client\'s position.' 
    },
    { 
      id: '2', 
      title: 'PROCEDURAL STATUS', 
      content: '[This section will be auto-generated by AI]\n\nSummarize the current procedural posture: case filing date, court and department, assigned judge, case management conference dates, trial date (if set), and any pending deadlines.' 
    },
    { 
      id: '3', 
      title: 'PLEADINGS', 
      content: '[This section will be auto-generated by AI]\n\nList all pleadings filed in the case by all parties:\n• Complaint (date filed, causes of action)\n• Answer (date filed, affirmative defenses)\n• Cross-complaints (if any)\n• Amendments to pleadings' 
    },
    { 
      id: '4', 
      title: 'COMMUNICATIONS', 
      content: '[This section will be auto-generated by AI]\n\nSummarize significant communications:\n• Correspondence with opposing counsel\n• Court communications\n• Client communications\n• Settlement discussions (if any)' 
    },
    { 
      id: '5', 
      title: 'DISCOVERY', 
      content: '[This section will be auto-generated by AI]\n\nDetail the discovery status:\n• Written discovery propounded and received\n• Depositions taken and scheduled\n• Outstanding discovery\n• Discovery disputes and motions' 
    },
    { 
      id: '6', 
      title: 'LIABILITY', 
      content: '[This section will be auto-generated by AI]\n\nAnalyze liability:\n• Strengths of plaintiff\'s case\n• Weaknesses/defenses\n• Comparative fault analysis\n• Likelihood of prevailing on liability' 
    },
    { 
      id: '7', 
      title: 'DAMAGES', 
      content: '[This section will be auto-generated by AI]\n\nDetail the damages:\n• Economic damages (medical expenses, lost wages, property damage)\n• Non-economic damages (pain and suffering)\n• Total damages assessment\n• Settlement value range' 
    },
    { 
      id: '8', 
      title: 'STRATEGY MOVING FORWARD', 
      content: '[This section will be auto-generated by AI]\n\nOutline the recommended strategy:\n• Discovery to be completed\n• Motions to be filed\n• Settlement negotiations\n• Trial preparation' 
    },
    { 
      id: '9', 
      title: 'FURTHER HANDLING', 
      content: '[This section will be auto-generated by AI]\n\nSpecify next steps and action items:\n• Immediate tasks\n• Upcoming deadlines\n• Client meetings needed\n• Recommended timeline' 
    },
  ]);
  const [draggedIndex, setDraggedIndex] = useState<number | null>(null);
  const [dragOverIndex, setDragOverIndex] = useState<number | null>(null);
  const [aiLoading, setAiLoading] = useState<string | null>(null);
  const [aiError, setAiError] = useState<string | null>(null);
  const [showPreview, setShowPreview] = useState(false);
  const [editingSection, setEditingSection] = useState<{id: string; title: string} | null>(null);
  const [currentCaseId, setCurrentCaseId] = useState<string | null>(null);
  const [currentCase, setCurrentCase] = useState<CaseFrontend | null>(null);
  const [saving, setSaving] = useState(false);
  const [saveSuccess, setSaveSuccess] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [userProfile, setUserProfile] = useState<UserProfile | null>(null);
  const [reportInfo, setReportInfo] = useState<ReportInfo>({
    caseName: '',
    caseNumber: '',
    reportDate: new Date().toISOString().split('T')[0],
    preparedBy: '',
    preparedFor: '',
  });
  const [hasGenerated, setHasGenerated] = useState(false);
  
  // Party identification for trial mode
  const [representationType, setRepresentationType] = useState<'plaintiff' | 'defendant'>('plaintiff');
  const [clientName, setClientName] = useState('');
  const [opposingPartyName, setOpposingPartyName] = useState('');

  const autoResizeTextarea = (textarea: HTMLTextAreaElement) => {
    textarea.style.height = 'auto';
    textarea.style.height = `${Math.max(192, textarea.scrollHeight)}px`; // min height of 192px (h-48)
  };

  const updateSection = (id: string, field: 'title' | 'content', value: string) => {
    setSections(sections.map(section => 
      section.id === id ? { ...section, [field]: value } : section
    ));
  };

  const addSection = () => {
    setSections([...sections, { 
      id: Date.now().toString(), 
      title: `Section ${sections.length + 1}`, 
      content: '' 
    }]);
  };

  const removeSection = (id: string) => {
    setSections(sections.filter(section => section.id !== id));
  };

  // Reset to start a new report (trial mode)
  const handleNewReport = () => {
    setSections([
      { 
        id: '0', 
        title: 'Case Summary', 
        content: 'Provide a comprehensive summary of the case including key facts, parties involved, claims, and current status. This will be used to generate the status report sections.' 
      },
      { 
        id: '1', 
        title: 'FACTUAL BACKGROUND', 
        content: '[This section will be auto-generated by AI]\n\nDescribe the key facts of the case, including the incident date, parties, what occurred, and how liability arose. Include relevant details that support your client\'s position.' 
      },
      { 
        id: '2', 
        title: 'PROCEDURAL STATUS', 
        content: '[This section will be auto-generated by AI]\n\nSummarize the current procedural posture: case filing date, court and department, assigned judge, case management conference dates, trial date (if set), and any pending deadlines.' 
      },
      { 
        id: '3', 
        title: 'PLEADINGS', 
        content: '[This section will be auto-generated by AI]\n\nList all pleadings filed in the case by all parties:\n• Complaint (date filed, causes of action)\n• Answer (date filed, affirmative defenses)\n• Cross-complaints (if any)\n• Amendments to pleadings' 
      },
      { 
        id: '4', 
        title: 'COMMUNICATIONS', 
        content: '[This section will be auto-generated by AI]\n\nSummarize significant communications:\n• Correspondence with opposing counsel\n• Court communications\n• Client communications\n• Settlement discussions (if any)' 
      },
      { 
        id: '5', 
        title: 'DISCOVERY', 
        content: '[This section will be auto-generated by AI]\n\nDetail the discovery status:\n• Written discovery propounded and received\n• Depositions taken and scheduled\n• Outstanding discovery\n• Discovery disputes and motions' 
      },
      { 
        id: '6', 
        title: 'LIABILITY', 
        content: '[This section will be auto-generated by AI]\n\nAnalyze liability:\n• Strengths of plaintiff\'s case\n• Weaknesses/defenses\n• Comparative fault analysis\n• Likelihood of prevailing on liability' 
      },
      { 
        id: '7', 
        title: 'DAMAGES', 
        content: '[This section will be auto-generated by AI]\n\nDetail the damages:\n• Economic damages (medical expenses, lost wages, property damage)\n• Non-economic damages (pain and suffering)\n• Total damages assessment\n• Settlement value range' 
      },
      { 
        id: '8', 
        title: 'STRATEGY MOVING FORWARD', 
        content: '[This section will be auto-generated by AI]\n\nOutline the recommended strategy:\n• Discovery to be completed\n• Motions to be filed\n• Settlement negotiations\n• Trial preparation' 
      },
      { 
        id: '9', 
        title: 'FURTHER HANDLING', 
        content: '[This section will be auto-generated by AI]\n\nSpecify next steps and action items:\n• Immediate tasks\n• Upcoming deadlines\n• Client meetings needed\n• Recommended timeline' 
      },
    ]);
    // Reset other form fields
    setReportInfo({
      caseName: '',
      caseNumber: '',
      reportDate: new Date().toISOString().split('T')[0],
      preparedBy: '',
      preparedFor: '',
    });
    setHasGenerated(false);
  };

  const handleAIAssist = async (sectionId: string) => {
    // Only allow for Case Summary section
    if (sectionId !== '0') {
      setAiError('AI generation is triggered from the Case Summary section');
      setTimeout(() => setAiError(null), 5000);
      return;
    }

    setAiLoading(sectionId);
    setAiError(null);

    try {
      const section = sections.find(s => s.id === sectionId);
      if (!section) return;

      const apiEndpoint = '/api/ai/populate-status-report';

      const requestBody = { 
        caseDescription: section.content,
        allSections: sections,
        // Include explicit party info for trial mode
        partyInfo: isTrialMode && clientName ? {
          representationType,
          clientName: clientName.trim(),
          opposingPartyName: opposingPartyName.trim()
        } : undefined
      };

      const response = await fetch(apiEndpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(requestBody),
      });

      if (!response.ok) {
        // Check if response is JSON
        const contentType = response.headers.get('content-type');
        let errorData;
        
        if (contentType && contentType.includes('application/json')) {
          errorData = await response.json();
        } else {
          // Response is HTML (error page), get text instead
          const text = await response.text();
          console.error('Non-JSON error response:', text.substring(0, 200));
          throw new Error(`Server error: ${response.status} ${response.statusText}. Please check your API configuration.`);
        }
        
        const errorMessage = errorData.error || 
                             errorData.details?.error?.message ||
                             `Server error: ${response.status} ${response.statusText}`;
        
        throw new Error(errorMessage);
      }

      const data = await response.json();
      
      // Update all sections with generated content
      if (data.sections) {
        setSections(prevSections => 
          prevSections.map(sec => {
            if (data.sections[sec.id]) {
              return { ...sec, content: data.sections[sec.id] };
            }
            return sec;
          })
        );
        // Mark as generated for trial mode UI
        setHasGenerated(true);
      }
    } catch (error) {
      console.error('AI Assist error:', error);
      setAiError(error instanceof Error ? error.message : 'An error occurred');
      setTimeout(() => setAiError(null), 5000);
    } finally {
      setAiLoading(null);
    }
  };

  const handleDragStart = (index: number) => {
    setDraggedIndex(index);
  };

  const handleDragOver = (e: React.DragEvent, index: number) => {
    e.preventDefault();
    setDragOverIndex(index);
  };

  const handleDragLeave = () => {
    setDragOverIndex(null);
  };

  const handleDrop = (e: React.DragEvent, dropIndex: number) => {
    e.preventDefault();
    
    if (draggedIndex === null || draggedIndex === dropIndex) {
      setDraggedIndex(null);
      setDragOverIndex(null);
      return;
    }

    // Prevent dropping Case Summary (id: '0') or dropping before Case Summary
    const draggedSection = sections[draggedIndex];
    if (draggedSection.id === '0' || dropIndex === 0) {
      setDraggedIndex(null);
      setDragOverIndex(null);
      return;
    }

    const newSections = [...sections];
    
    // Remove the dragged item
    newSections.splice(draggedIndex, 1);
    
    // Insert at new position (but never at index 0)
    newSections.splice(dropIndex, 0, draggedSection);
    
    setSections(newSections);
    setDraggedIndex(null);
    setDragOverIndex(null);
  };

  const handleDragEnd = () => {
    setDraggedIndex(null);
    setDragOverIndex(null);
  };

  // Auto-resize textareas when sections change
  useEffect(() => {
    const textareas = document.querySelectorAll('textarea');
    textareas.forEach((textarea) => {
      autoResizeTextarea(textarea as HTMLTextAreaElement);
    });
  }, [sections]);

  // Load user profile for letterhead info (only for authenticated users)
  useEffect(() => {
    // Skip profile loading in trial mode - no user to load
    if (isTrialMode) return;
    
    const loadUserProfile = async () => {
      try {
        const profile = await userProfileStorage.getProfile();
        if (profile) {
          setUserProfile(profile);
        }
      } catch (error) {
        console.error('Error loading user profile:', error);
      }
    };
    loadUserProfile();
  }, [isTrialMode]);

  // Auto-populate report info from user profile for logged-in users
  useEffect(() => {
    if (!isTrialMode && userProfile) {
      setReportInfo(prev => ({
        ...prev,
        preparedBy: userProfile.fullName || '',
      }));
    }
  }, [isTrialMode, userProfile]);

  // Load case data from caseId if provided
  useEffect(() => {
    const loadCase = async () => {
      const caseId = searchParams?.get('caseId');
      
      // SECURITY: Block real case IDs in trial mode
      if (caseId && isTrialMode && !isTrialCaseId(caseId)) {
        console.warn('[SECURITY] Attempted to access real case ID in trial mode - blocked');
        return;
      }
      
      if (caseId && !isTrialMode && canAccessDatabase()) {
        // SECURITY: Validate UUID format before database operations
        if (!UUID_REGEX.test(caseId)) {
          console.warn('[SECURITY] Invalid case ID format - blocked');
          return;
        }
        
        const supabase = createClient();
        const { data: { user } } = await supabase.auth.getUser();
        
        if (user) {
          const foundCase = await supabaseCaseStorage.getCase(caseId);
          if (foundCase) {
            console.log(`[AUDIT] Status report page accessed for case: ${caseId}`);
            setCurrentCaseId(caseId);
            setCurrentCase(foundCase);
            
            // Load saved status report sections if they exist
            if (foundCase.statusReportSections && foundCase.statusReportSections.length > 0) {
              setSections(foundCase.statusReportSections);
            } else if (foundCase.facts) {
              // No saved sections but have facts - populate case description only, clear others
              setSections(prevSections =>
                prevSections.map(section =>
                  section.id === '0'
                    ? { ...section, content: foundCase.facts || '' }
                    : { ...section, content: '' }
                )
              );
            }
            
            // Populate report info from case
            setReportInfo(prev => ({
              ...prev,
              caseName: foundCase.caseName || '',
              caseNumber: foundCase.caseNumber || '',
            }));
          }
        }
      }
    };
    
    loadCase();
  }, [searchParams, isTrialMode, canAccessDatabase, isTrialCaseId]);

  // Save draft - secure implementation with no data leakage
  const handleSaveDraft = async () => {
    // SECURITY: Require a valid case ID
    if (!currentCaseId) {
      setSaveError('No case selected. Please access this page from the case dashboard.');
      setTimeout(() => setSaveError(null), 5000);
      return;
    }

    // SECURITY: Validate UUID format to prevent injection
    if (!UUID_REGEX.test(currentCaseId)) {
      console.warn('[SECURITY] Attempted to save with invalid case ID format - blocked');
      setSaveError('Invalid case ID. Cannot save to database.');
      setTimeout(() => setSaveError(null), 5000);
      return;
    }

    // SECURITY: Block saves in trial mode
    if (isTrialMode) {
      setSaveError('Saving is disabled in trial mode.');
      setTimeout(() => setSaveError(null), 5000);
      return;
    }

    setSaving(true);
    setSaveSuccess(false);
    setSaveError(null);

    try {
      // SECURITY: supabaseCaseStorage.updateCase uses Row Level Security
      // which ensures user can only update their own cases
      const result = await supabaseCaseStorage.updateCase(currentCaseId, {
        statusReportSections: sections,
      });

      if (result) {
        setSaveSuccess(true);
        console.log(`[AUDIT] Status report draft saved for case: ${currentCaseId}`);
        setTimeout(() => setSaveSuccess(false), 3000);
      } else {
        setSaveError('Failed to save draft. Please try again.');
        setTimeout(() => setSaveError(null), 5000);
      }
    } catch (error) {
      console.error('Error saving draft:', error);
      setSaveError('An error occurred while saving. Please try again.');
      setTimeout(() => setSaveError(null), 5000);
    } finally {
      setSaving(false);
    }
  };

  // Split sections into Case Summary and other sections
  const caseDescription = sections.find(s => s.id === '0');
  const otherSections = sections.filter(s => s.id !== '0');

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-blue-50">
      <Header />
      <TrialModeBanner />
      
      {/* Case Name Header - Only show when accessed from case dashboard */}
      {currentCase && !isTrialMode && searchParams?.get('caseId') && (
        <div className="bg-gradient-to-r from-blue-600 to-blue-700 text-white py-4 shadow-md">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-3">
                <Link 
                  href={`/dashboard/cases/${currentCase.id}`}
                  className="hover:opacity-80 transition-opacity"
                >
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                  </svg>
                </Link>
                <div>
                  <h2 className="text-xl font-bold">{currentCase.caseName}</h2>
                  {currentCase.caseNumber && (
                    <p className="text-sm text-blue-100">Case #: {currentCase.caseNumber}</p>
                  )}
                </div>
              </div>
              <Link
                href={`/dashboard/cases/${currentCase.id}`}
                className="text-sm hover:underline text-blue-100"
              >
                Back to Case
              </Link>
            </div>
          </div>
        </div>
      )}

      {/* Hero Section */}
      <section className="bg-gradient-to-br from-blue-50 via-white to-blue-50 pt-16 pb-8">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-4xl mx-auto">
            <h1 className="text-5xl md:text-6xl font-bold mb-8 leading-tight">
              <span className="gradient-text">Status Report</span> <span className="text-gray-900">Generator</span>
            </h1>
            <p className="text-xl md:text-2xl text-slate-600 mb-12 leading-relaxed">
              Create comprehensive case status reports with AI-powered analysis and professional formatting.
            </p>
          </div>
        </div>
      </section>

      <div className="min-h-screen p-6 bg-gradient-to-br from-blue-50 via-white to-blue-50">
        <div className="max-w-7xl mx-auto">
          {/* Report Information Card - Show for logged-in users or trial mode after generation */}
          {((!isTrialMode && userProfile) || (isTrialMode && hasGenerated)) && (
            <div className="mb-8">
              <div className="glass-strong p-6 rounded-2xl hover:shadow-2xl transition-all duration-300">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-3">
                    <div className="text-blue-600">
                      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                      </svg>
                    </div>
                    <div>
                      <h2 className="text-xl font-semibold text-gray-900">Report Information</h2>
                      <p className="text-sm text-gray-500">
                        Details about this status report
                      </p>
                    </div>
                  </div>
                </div>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {/* Case Name */}
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Case Name</label>
                    <input
                      type="text"
                      value={reportInfo.caseName}
                      onChange={(e) => setReportInfo(prev => ({ ...prev, caseName: e.target.value }))}
                      className="w-full px-4 py-2 bg-white border border-gray-200 rounded-xl text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      placeholder="e.g., Smith v. Jones"
                    />
                  </div>
                  
                  {/* Case Number */}
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Case Number</label>
                    <input
                      type="text"
                      value={reportInfo.caseNumber}
                      onChange={(e) => setReportInfo(prev => ({ ...prev, caseNumber: e.target.value }))}
                      className="w-full px-4 py-2 bg-white border border-gray-200 rounded-xl text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      placeholder="Case number"
                    />
                  </div>
                  
                  {/* Report Date */}
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Report Date</label>
                    <input
                      type="date"
                      value={reportInfo.reportDate}
                      onChange={(e) => setReportInfo(prev => ({ ...prev, reportDate: e.target.value }))}
                      className="w-full px-4 py-2 bg-white border border-gray-200 rounded-xl text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    />
                  </div>
                  
                  {/* Prepared By */}
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Prepared By</label>
                    <input
                      type="text"
                      value={reportInfo.preparedBy}
                      onChange={(e) => setReportInfo(prev => ({ ...prev, preparedBy: e.target.value }))}
                      className="w-full px-4 py-2 bg-white border border-gray-200 rounded-xl text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      placeholder="Your name"
                    />
                  </div>
                  
                  {/* Prepared For */}
                  <div className="md:col-span-2">
                    <label className="block text-sm font-medium text-gray-700 mb-1">Prepared For</label>
                    <input
                      type="text"
                      value={reportInfo.preparedFor}
                      onChange={(e) => setReportInfo(prev => ({ ...prev, preparedFor: e.target.value }))}
                      className="w-full px-4 py-2 bg-white border border-gray-200 rounded-xl text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      placeholder="Client name or supervising attorney"
                    />
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Party Information Section - Trial Mode Only */}
          {isTrialMode && (
            <div className="mb-8">
              <div className="glass-strong p-6 rounded-2xl">
                <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
                  <svg className="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
                  </svg>
                  Party Information
                </h3>
                
                {/* Representation Type */}
                <div className="mb-4">
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    You Represent:
                  </label>
                  <div className="flex gap-4">
                    <label className="flex items-center gap-2 cursor-pointer">
                      <input
                        type="radio"
                        name="representationType"
                        value="plaintiff"
                        checked={representationType === 'plaintiff'}
                        onChange={() => setRepresentationType('plaintiff')}
                        className="w-4 h-4 text-blue-600 focus:ring-blue-500"
                      />
                      <span className="text-gray-700">Plaintiff / Claimant</span>
                    </label>
                    <label className="flex items-center gap-2 cursor-pointer">
                      <input
                        type="radio"
                        name="representationType"
                        value="defendant"
                        checked={representationType === 'defendant'}
                        onChange={() => setRepresentationType('defendant')}
                        className="w-4 h-4 text-blue-600 focus:ring-blue-500"
                      />
                      <span className="text-gray-700">Defendant / Respondent</span>
                    </label>
                  </div>
                </div>
                
                {/* Party Names */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      {representationType === 'plaintiff' ? 'Your Client (Plaintiff)' : 'Your Client (Defendant)'}
                    </label>
                    <input
                      type="text"
                      value={clientName}
                      onChange={(e) => setClientName(e.target.value)}
                      placeholder={representationType === 'plaintiff' ? 'e.g., John Smith' : 'e.g., ABC Company, LLC'}
                      className="w-full px-4 py-2 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-900 placeholder-gray-400"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      {representationType === 'plaintiff' ? 'Opposing Party (Defendant)' : 'Opposing Party (Plaintiff)'}
                    </label>
                    <input
                      type="text"
                      value={opposingPartyName}
                      onChange={(e) => setOpposingPartyName(e.target.value)}
                      placeholder={representationType === 'plaintiff' ? 'e.g., XYZ Corporation, Inc.' : 'e.g., Jane Doe'}
                      className="w-full px-4 py-2 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-900 placeholder-gray-400"
                    />
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Case Summary Section - Separate at Top */}
          {caseDescription && (
            <div className="mb-8">
              <div className="glass-strong p-6 rounded-2xl hover:shadow-2xl transition-all duration-300 relative">
                <div className="flex justify-between items-start mb-4 gap-3">
                  <div className="text-gray-400 flex items-center pt-1">
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                  </div>
                  <input
                    type="text"
                    value={caseDescription.title}
                    onChange={(e) => updateSection(caseDescription.id, 'title', e.target.value)}
                    className="text-xl font-semibold text-gray-900 bg-transparent border-none outline-none flex-1 placeholder-gray-400"
                    placeholder="Section Title"
                  />
                </div>
                <div className="relative">
                  <textarea
                    value={caseDescription.content}
                    onChange={(e) => {
                      updateSection(caseDescription.id, 'content', e.target.value);
                      autoResizeTextarea(e.target as HTMLTextAreaElement);
                    }}
                    onInput={(e) => autoResizeTextarea(e.target as HTMLTextAreaElement)}
                    ref={(textarea) => {
                      if (textarea) {
                        autoResizeTextarea(textarea);
                      }
                    }}
                    className="w-full min-h-48 p-4 bg-white border border-gray-200 rounded-xl text-gray-900 placeholder-gray-400 resize-none focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 overflow-hidden"
                    placeholder="Enter a comprehensive case summary here..."
                  />
                </div>
                {aiError && (
                  <div className="mt-2 text-sm text-red-600 bg-red-50 p-2 rounded border border-red-200">
                    {aiError}
                  </div>
                )}
              </div>
            </div>
          )}

          {/* AI Generation Button - Show after Case Summary for both trial mode and logged-in users */}
          {caseDescription && (
            <button
              onClick={() => handleAIAssist('0')}
              disabled={aiLoading === '0' || !caseDescription.content.trim() || caseDescription.content.length < 50}
              className="w-full mb-8 py-4 px-6 bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white rounded-xl font-semibold transition-all duration-300 flex items-center justify-center space-x-2 disabled:opacity-50 disabled:cursor-not-allowed shadow-lg hover:shadow-xl"
            >
              {aiLoading === '0' ? (
                <>
                  <svg className="w-5 h-5 animate-spin text-white" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                  <span>Generating Status Report...</span>
                </>
              ) : (
                <>
                  <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
                  </svg>
                  <span>Generate AI-Powered Status Report</span>
                </>
              )}
            </button>
          )}

          {/* Divider and Status Report Sections - Hidden until generated in trial mode */}
          {(!isTrialMode || hasGenerated) && (
          <>
          {/* Divider */}
          <div className="mb-8 flex items-center gap-4">
            <div className="flex-1 h-px bg-gradient-to-r from-transparent via-blue-200 to-transparent"></div>
            <span className="text-gray-600 text-sm font-medium">Status Report Sections</span>
            <div className="flex-1 h-px bg-gradient-to-r from-transparent via-blue-200 to-transparent"></div>
          </div>

          {/* Other Cards Stack */}
          <div className="flex flex-col gap-6 mb-8">
            {otherSections.map((section) => {
              // Find original index for drag/drop
              const originalIndex = sections.findIndex(s => s.id === section.id);
              return (
                <div
                  key={section.id}
                  draggable
                  onDragStart={() => handleDragStart(originalIndex)}
                  onDragOver={(e) => handleDragOver(e, originalIndex)}
                  onDragLeave={handleDragLeave}
                  onDrop={(e) => handleDrop(e, originalIndex)}
                  onDragEnd={handleDragEnd}
                  className={`glass-strong p-6 rounded-2xl hover:shadow-2xl transition-all duration-300 relative cursor-move ${
                    draggedIndex === originalIndex ? 'opacity-50 scale-95' : ''
                  } ${
                    dragOverIndex === originalIndex && draggedIndex !== originalIndex ? 'border-2 border-blue-500 border-dashed scale-105' : ''
                  }`}
                >
                  <div className="flex justify-between items-start mb-4 gap-3">
                    {/* Drag Handle */}
                    <div className="text-gray-400 hover:text-gray-600 transition-colors flex items-center pt-1">
                      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 8h16M4 16h16" />
                      </svg>
                    </div>
                    <input
                      type="text"
                      value={section.title}
                      onChange={(e) => updateSection(section.id, 'title', e.target.value)}
                      className="text-xl font-semibold text-gray-900 bg-transparent border-none outline-none flex-1 placeholder-gray-400"
                      placeholder="Section Title"
                    />
                    {sections.length > 1 && (
                      <button
                        onClick={() => removeSection(section.id)}
                        className="text-gray-400 hover:text-red-600 transition-colors p-1"
                        aria-label="Remove section"
                      >
                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                      </button>
                    )}
                  </div>
                  <div className="relative">
                    <textarea
                      value={section.content}
                      onChange={(e) => {
                        updateSection(section.id, 'content', e.target.value);
                        autoResizeTextarea(e.target as HTMLTextAreaElement);
                      }}
                      onInput={(e) => autoResizeTextarea(e.target as HTMLTextAreaElement)}
                      ref={(textarea) => {
                        if (textarea) {
                          autoResizeTextarea(textarea);
                        }
                      }}
                      className="w-full min-h-48 p-4 pr-14 bg-white border border-gray-200 rounded-xl text-gray-900 placeholder-gray-400 resize-none focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 overflow-hidden"
                      placeholder="Enter section content here..."
                    />
                    {/* AI Sparkle Button - Opens AI Edit Chat */}
                    <button
                      onClick={() => setEditingSection({ id: section.id, title: section.title })}
                      className="absolute bottom-3 right-3 p-2.5 bg-gradient-to-br from-blue-600 to-blue-800 rounded-full shadow-lg hover:shadow-xl hover:scale-110 transition-all duration-300 group"
                      aria-label="Edit with AI"
                      title="Edit with AI Assistant"
                    >
                        <svg 
                          className="w-4 h-4 text-white group-hover:rotate-12 transition-transform duration-300" 
                          fill="currentColor" 
                          viewBox="0 0 24 24"
                        >
                          <path d="M12 0L13.5 8.5L22 10L13.5 11.5L12 20L10.5 11.5L2 10L10.5 8.5L12 0Z" />
                          <path d="M6 4L6.5 6.5L9 7L6.5 7.5L6 10L5.5 7.5L3 7L5.5 6.5L6 4Z" />
                          <path d="M18 14L18.5 16.5L21 17L18.5 17.5L18 20L17.5 17.5L15 17L17.5 16.5L18 14Z" />
                        </svg>
                    </button>
                  </div>
                </div>
              );
            })}
          </div>

          {/* Add Section Button */}
          <div className="mb-8 flex justify-center">
            <button
              onClick={addSection}
              className="px-6 py-3 bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white rounded-full font-semibold transition-all duration-300 shadow-lg hover:shadow-xl"
            >
              + Add Section
            </button>
          </div>

          {/* Action Buttons */}
          <div className="glass p-6 rounded-2xl flex flex-col gap-4">
            {/* Error message stays as banner */}
            {saveError && (
              <div className="text-sm text-red-600 bg-red-50 p-3 rounded-lg border border-red-200 flex items-center gap-2">
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
                {saveError}
              </div>
            )}
            
            <div className="flex gap-4 justify-end items-center">
              {!isTrialMode && (
                <button 
                  onClick={handleSaveDraft}
                  disabled={saving || !currentCaseId}
                  className={`px-6 py-3 rounded-full font-semibold transition-all duration-300 flex items-center gap-2 ${
                    saving ? 'opacity-50 cursor-not-allowed' : ''
                  } ${!currentCaseId 
                    ? 'opacity-50 cursor-not-allowed bg-gray-100 text-gray-400 border border-gray-200' 
                    : saveSuccess 
                      ? 'bg-green-600 text-white'
                      : 'bg-white border border-gray-300 text-gray-700 hover:bg-gray-50'
                  }`}
                  title={!currentCaseId ? 'Access from case dashboard to enable saving' : 'Save draft to case'}
                >
                  {saving ? (
                    <>
                      <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                      </svg>
                      <span>Saving...</span>
                    </>
                  ) : saveSuccess ? (
                    <>
                      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                      </svg>
                      <span>Saved!</span>
                    </>
                  ) : (
                    <>
                      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4" />
                      </svg>
                      <span>Save Draft</span>
                    </>
                  )}
                </button>
              )}
              {/* New Report Button */}
              <button
                onClick={handleNewReport}
                className="px-6 py-3 bg-white border border-gray-300 text-gray-700 rounded-full font-semibold hover:bg-gray-50 transition-all duration-300 flex items-center gap-2"
              >
                <RotateCcw className="w-4 h-4" />
                <span>New Report</span>
              </button>
              <button 
                onClick={() => setShowPreview(true)}
                className="px-6 py-3 bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white rounded-full font-semibold transition-all duration-300 shadow-lg hover:shadow-xl"
              >
              Preview Report
            </button>
            </div>
          </div>
          </>
          )}

          {/* Legal Disclaimer */}
          <div className="glass p-6 rounded-2xl bg-amber-50 border border-amber-200 mt-6">
            <h4 className="font-medium text-amber-800 mb-2">⚠️ Note</h4>
            <p className="text-amber-800 text-sm">
              This status report is AI-generated and should be reviewed for accuracy before distribution. 
              Verify all dates, facts, and assessments against your case file. 
              The liability and damages analysis represents an AI assessment and should be confirmed by the handling attorney.
            </p>
          </div>
        </div>
      </div>
      
      <Footer />

      {/* Preview Modal */}
      <PreviewModal
        isOpen={showPreview}
        onClose={() => setShowPreview(false)}
        sections={sections}
        reportInfo={reportInfo}
        userProfile={isTrialMode ? undefined : userProfile || undefined}
      />

      {/* AI Edit Chat Modal */}
      {editingSection && (
        <AIEditChatModal
          isOpen={!!editingSection}
          onClose={() => setEditingSection(null)}
          sectionId={editingSection.id}
          sectionTitle={editingSection.title}
          currentContent={sections.find(s => s.id === editingSection.id)?.content || ''}
          caseDescription={sections.find(s => s.id === '0')?.content || ''}
          caseId={currentCaseId || ''}
          onApplyEdit={(newContent) => {
            updateSection(editingSection.id, 'content', newContent);
            setEditingSection(null);
          }}
          isTrialMode={isTrialMode}
        />
      )}
    </div>
  );
}

